/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { AttendanceRuleConfigController } from '../../controller/xbt-platform-salary-service/attendance-rule-config.controller'

export class AttendanceRuleConfigService {
    /**
     * 查询全部
     */
    @Request({
        server: AttendanceRuleConfigController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: AttendanceRuleConfigController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 更新
     */
    @Request({
        server: AttendanceRuleConfigController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
