/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { EmployeeInnerRewardController } from '../../controller/xbt-platform-salary-service/employee-inner-reward.controller'

export class EmployeeInnerRewardService {
    /**
     * 申请
     */
    @Request({
        server: EmployeeInnerRewardController.apply
    })
    public apply(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 确认
     */
    @Request({
        server: EmployeeInnerRewardController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * create
     */
    @Request({
        server: EmployeeInnerRewardController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * delete
     */
    @Request({
        server: EmployeeInnerRewardController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 驳回
     */
    @Request({
        server: EmployeeInnerRewardController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get All
     */
    @Request({
        server: EmployeeInnerRewardController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get List
     */
    @Request({
        server: EmployeeInnerRewardController.getList
    })
    public getList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * update
     */
    @Request({
        server: EmployeeInnerRewardController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
