/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { EmployeeSalaryInformController } from '../../controller/xbt-platform-salary-service/employee-salary-inform.controller'

export class EmployeeSalaryInformService {
    /**
     * 员工确认
     */
    @Request({
        server: EmployeeSalaryInformController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 员工否认
     */
    @Request({
        server: EmployeeSalaryInformController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 多人下发
     */
    @Request({
        server: EmployeeSalaryInformController.informList
    })
    public informList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 单人下发
     */
    @Request({
        server: EmployeeSalaryInformController.inform
    })
    public inform(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
