/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { ManagementScopeController } from '../../controller/xbt-platform-salary-service/management-scope.controller'

export class ManagementScopeService {
    /**
     * 创建
     */
    @Request({
        server: ManagementScopeController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 删除
     */
    @Request({
        server: ManagementScopeController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询全部
     */
    @Request({
        server: ManagementScopeController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: ManagementScopeController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取当前登录用户的管理范围信息
     */
    @Request({
        server: ManagementScopeController.getMineManagementScope
    })
    public getMineManagementScope(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 分页查询
     */
    @Request({
        server: ManagementScopeController.query
    })
    public query(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 更新
     */
    @Request({
        server: ManagementScopeController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
