/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { MonthBonusController } from '../../controller/xbt-platform-salary-service/month-bonus.controller'

export class MonthBonusService {
    /**
     * create
     */
    @Request({
        server: MonthBonusController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * delete
     */
    @Request({
        server: MonthBonusController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
