/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { ReportController } from '../../controller/xbt-platform-salary-service/report.controller'

export class ReportService {
    /**
     * findOne
     */
    @Request({
        server: ReportController.getByEmployee
    })
    public getByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
