/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SalaryValueController } from '../../controller/xbt-platform-salary-service/salary-value.controller'

export class SalaryValueService {
    /**
     * calculation by employee
     */
    @Request({
        server: SalaryValueController.calcByEmployee
    })
    public calcByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * calculation by id
     */
    @Request({
        server: SalaryValueController.calcById
    })
    public calcById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * create for employee
     */
    @Request({
        server: SalaryValueController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 核算列表
     */
    @Request({
        server: SalaryValueController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: SalaryValueController.getByEmployee
    })
    public getByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: SalaryValueController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的工资
     */
    @Request({
        server: SalaryValueController.mySalary
    })
    public mySalary(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * update
     */
    @Request({
        server: SalaryValueController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
