/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SalaryConfirmFlowController } from '../../controller/xbt-platform-salary-service/salary-confirm-flow.controller'

export class SalaryConfirmFlowService {
    /**
     * 审核同意
     */
    @Request({
        server: SalaryConfirmFlowController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 创建审批
     */
    @Request({
        server: SalaryConfirmFlowController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审核不同意
     */
    @Request({
        server: SalaryConfirmFlowController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审批列表
     */
    @Request({
        server: SalaryConfirmFlowController.getAllConfirm
    })
    public getAllConfirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的流程
     */
    @Request({
        server: SalaryConfirmFlowController.getList
    })
    public getList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
