/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SocialSecurityController } from '../../controller/xbt-platform-salary-service/social-security.controller'

export class SocialSecurityService {
    /**
     * export excel
     */
    @Request({
        server: SocialSecurityController.export
    })
    public export(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get All
     */
    @Request({
        server: SocialSecurityController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: SocialSecurityController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * import excel
     */
    @Request({
        server: SocialSecurityController.import
    })
    public import(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
