/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SysDictController } from '../../controller/xbt-platform-salary-service/sys-dict.controller'

export class SysDictService {
    /**
     * get All
     */
    @Request({
        server: SysDictController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: SysDictController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get Detail
     */
    @Request({
        server: SysDictController.getDetailAll
    })
    public getDetailAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * find Detail One
     */
    @Request({
        server: SysDictController.getDetail
    })
    public getDetail(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
