/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { TaxController } from '../../controller/xbt-platform-salary-service/tax.controller'

export class TaxService {
    /**
     * export excel
     */
    @Request({
        server: TaxController.export
    })
    public export(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get All
     */
    @Request({
        server: TaxController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: TaxController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * import excel
     */
    @Request({
        server: TaxController.import
    })
    public import(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get Tax SocialSecurity
     */
    @Request({
        server: TaxController.taxAndSocialSecurity
    })
    public taxAndSocialSecurity(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
