/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { TestController } from '../../controller/xbt-platform-salary-service/test.controller'

export class TestService {
    /**
     * 核算基数按月返Json
     */
    @Request({
        server: TestController.getMonthBonusRule
    })
    public getMonthBonusRule(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 核算基数MvelJson
     */
    @Request({
        server: TestController.getMvelRuleSource
    })
    public getMvelRuleSource(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 生成指定月份工资
     */
    @Request({
        server: TestController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 删除指定月份工资
     */
    @Request({
        server: TestController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
