/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'storage'
const service = ''
const gateway = 'authorization'

export const StorageController = {
    // 获取文件存储配置
    getStorageConfig: {
        gateway,
        service,
        controller,
        path: '/storage/config/{storage}',
        action: 'getStorageConfig',
        type: RequestMethod.Get
    },
    // 获取文件存储授权
    getStorageCredential: {
        gateway,
        service,
        controller,
        path: '/storage/credential/{storage}',
        action: 'getStorageCredential',
        type: RequestMethod.Get
    }
}
