/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { EmployeeController } from '../../controller/xbt-platform-kyb-service/employee.controller'

export class EmployeeService {
    /**
     * 随机获取一个员工信息
     */
    @Request({
        server: EmployeeController.findDefault
    })
    public findDefault(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: EmployeeController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取个人信息
     */
    @Request({
        server: EmployeeController.getMine
    })
    public getMine(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取员工小程序码
     */
    @Request({
        server: EmployeeController.getMiniAppCode
    })
    public getMiniAppCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 更新我的个人信息
     */
    @Request({
        server: EmployeeController.updateMine
    })
    public updateMine(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
