/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SMSController } from '../../controller/xbt-platform-kyb-service/s-m-s.controller'

export class SMSService {
    /**
     * 发送一个后台不验证的验证码
     */
    @Request({
        server: SMSController.orderRefund
    })
    public orderRefund(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
