/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { UserController } from '../../controller/xbt-platform-kyb-service/user.controller'

export class UserService {
    /**
     * 添加患者信息绑定
     */
    @Request({
        server: UserController.addPatient
    })
    public addPatient(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 修改用户可编辑项目
     */
    @Request({
        server: UserController.changProfile
    })
    public changProfile(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: UserController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取当前登录用户信息
     */
    @Request({
        server: UserController.getMineUser
    })
    public getMineUser(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用UnionId登录
     */
    @Request({
        server: UserController.loginByUnionId
    })
    public loginByUnionId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 发送绑定验证码
     */
    @Request({
        server: UserController.sendBindingVerificationCode
    })
    public sendBindingVerificationCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 验证手机号/验证码
     */
    @Request({
        server: UserController.verificationBindingCode
    })
    public verificationBindingCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
