/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { WxMaController } from '../../controller/xbt-platform-kyb-service/wx-ma.controller'

export class WxMaService {
    /**
     * authGet
     */
    @Request({
        server: WxMaController.authGet
    })
    public authGet(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * post
     */
    @Request({
        server: WxMaController.post
    })
    public post(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取用户的UnionId
     */
    @Request({
        server: WxMaController.getUnionId
    })
    public getUnionId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 授权获取微信用户信息
     */
    @Request({
        server: WxMaController.getWxMpUserInfo
    })
    public getWxMpUserInfo(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getWxaCodeFile
     */
    @Request({
        server: WxMaController.getWxaCodeFile
    })
    public getWxaCodeFile(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getWxaCodeLimitedFile
     */
    @Request({
        server: WxMaController.getWxaCodeLimitedFile
    })
    public getWxaCodeLimitedFile(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * phone
     */
    @Request({
        server: WxMaController.phone
    })
    public phone(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
