/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'agent-appointment-order'
const service = 'xbt-platform-kyb-service'

export const AgentAppointmentOrderController = {
    // 代理预约提交
    agentAppointmentOrderPost: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/agentAppointmentOrderPost',
        action: 'agentAppointmentOrderPost',
        type: RequestMethod.Post
    },
    // 创建
    create: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // 删除
    delete: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // 查询全部
    getAll: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 分页查询
    query: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/query',
        action: 'query',
        type: RequestMethod.Get
    },
    // 查询员工的预约记录
    queryByEmployee: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/queryByEmployee',
        action: 'queryByEmployee',
        type: RequestMethod.Get
    },
    // 查询客户的预约记录
    queryByUser: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/queryByUser',
        action: 'queryByUser',
        type: RequestMethod.Get
    },
    // 更新
    update: {
        service,
        controller,
        path: '/api/agentAppointmentOrder/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
