/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee'
const service = 'xbt-platform-kyb-service'

export const EmployeeController = {
    // 随机获取一个员工信息
    findDefault: {
        service,
        controller,
        path: '/api/employee/findDefault',
        action: 'findDefault',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/employee/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 获取个人信息
    getMine: {
        service,
        controller,
        path: '/api/employee/getMine',
        action: 'getMine',
        type: RequestMethod.Get
    },
    // 获取员工小程序码
    getMiniAppCode: {
        service,
        controller,
        path: '/api/employee/getMiniAppCode/{id}',
        action: 'getMiniAppCode',
        type: RequestMethod.Get
    },
    // 更新我的个人信息
    updateMine: {
        service,
        controller,
        path: '/api/employee/updateMine',
        action: 'updateMine',
        type: RequestMethod.Put
    }
}
