/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'external-api-config'
const service = 'xbt-platform-kyb-service'

export const ExternalApiConfigController = {
    // 创建
    create: {
        service,
        controller,
        path: '/api/externalApiConfig/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // 删除
    delete: {
        service,
        controller,
        path: '/api/externalApiConfig/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // 查询全部
    getAll: {
        service,
        controller,
        path: '/api/externalApiConfig/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/externalApiConfig/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 分页查询
    query: {
        service,
        controller,
        path: '/api/externalApiConfig/query',
        action: 'query',
        type: RequestMethod.Get
    },
    // 更新
    update: {
        service,
        controller,
        path: '/api/externalApiConfig/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
