/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'wx-ma'
const service = 'xbt-platform-kyb-service'

export const WxMaController = {
    // authGet
    authGet: {
        service,
        controller,
        path: '/api/wxMaController/authGet',
        action: 'authGet',
        type: RequestMethod.Get
    },
    // post
    post: {
        service,
        controller,
        path: '/api/wxMaController/authGet',
        action: 'post',
        type: RequestMethod.Post
    },
    // 获取用户的UnionId
    getUnionId: {
        service,
        controller,
        path: '/api/wxMaController/getUnionId',
        action: 'getUnionId',
        type: RequestMethod.Post
    },
    // 授权获取微信用户信息
    getWxMpUserInfo: {
        service,
        controller,
        path: '/api/wxMaController/getWxMpUserInfo',
        action: 'getWxMpUserInfo',
        type: RequestMethod.Post
    },
    // getWxaCodeFile
    getWxaCodeFile: {
        service,
        controller,
        path: '/api/wxMaController/getWxaCodeFile',
        action: 'getWxaCodeFile',
        type: RequestMethod.Get
    },
    // getWxaCodeLimitedFile
    getWxaCodeLimitedFile: {
        service,
        controller,
        path: '/api/wxMaController/getWxaCodeLimitedFile',
        action: 'getWxaCodeLimitedFile',
        type: RequestMethod.Get
    },
    // phone
    phone: {
        service,
        controller,
        path: '/api/wxMaController/phone',
        action: 'phone',
        type: RequestMethod.Get
    }
}
