/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'call-back'
const service = 'xbt-platform-dingtalk-service'

export const CallBackController = {
    // callback
    callback: {
        service,
        controller,
        path: '/api/callback/1129547021',
        action: 'callback',
        type: RequestMethod.Post
    }
}
