/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee'
const service = 'xbt-platform-dingtalk-service'

export const EmployeeController = {
    // 查询全部员工
    getAll: {
        service,
        controller,
        path: '/api/employee/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/employee/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 通过ID列表查询员工信息
    getEmployeeByIds: {
        service,
        controller,
        path: '/api/employee/getEmployeeByIds',
        action: 'getEmployeeByIds',
        type: RequestMethod.Post
    },
    // 通过姓名和部门id查询
    getEmployeeIds: {
        service,
        controller,
        path: '/api/employee/getEmployeeByNameAndDept',
        action: 'getEmployeeIds',
        type: RequestMethod.Post
    },
    // 使用部门ID查询用户列表
    getEmployeesByDepartmentId: {
        service,
        controller,
        path: '/api/employee/getEmployeesByDepartmentId/{id}',
        action: 'getEmployeesByDepartmentId',
        type: RequestMethod.Get
    },
    // 使用部门ID列表查询用户列表
    getEmployeesByDepartmentIds: {
        service,
        controller,
        path: '/api/employee/getEmployeesByDepartmentIds/{ids}',
        action: 'getEmployeesByDepartmentIds',
        type: RequestMethod.Get
    },
    // 使用ID查询数据库中的同步员工
    getLocalById: {
        service,
        controller,
        path: '/api/employee/getLocalById/{id}',
        action: 'getLocalById',
        type: RequestMethod.Get
    },
    // 同步全部员工
    syncAllEmployee: {
        service,
        controller,
        path: '/api/employee/syncAllEmployee',
        action: 'syncAllEmployee',
        type: RequestMethod.Put
    }
}
