/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'process-instance'
const service = 'xbt-platform-dingtalk-service'

export const ProcessInstanceController = {
    // 创建流程实例
    processInstanceCreate: {
        service,
        controller,
        path: '/api/processInstance/processInstanceCreate',
        action: 'processInstanceCreate',
        type: RequestMethod.Post
    }
}
