/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'role'
const service = 'xbt-platform-dingtalk-service'

export const RoleController = {
    // 获取所有角色
    getAllRoles: {
        service,
        controller,
        path: '/api/role/getAllRoles',
        action: 'getAllRoles',
        type: RequestMethod.Get
    },
    // 获取钉钉中所有角色
    getAllRolesByDingTalk: {
        service,
        controller,
        path: '/api/role/getAllRolesByDingTalk',
        action: 'getAllRolesByDingTalk',
        type: RequestMethod.Get
    },
    // 通过角色分组ID获取角色列表
    getRolesByGroupId: {
        service,
        controller,
        path: '/api/role/getRolesByGroupId/{groupId}',
        action: 'getRolesByGroupId',
        type: RequestMethod.Get
    },
    // 同步全部角色
    syncAllRoles: {
        service,
        controller,
        path: '/api/role/syncAllRoles',
        action: 'syncAllRoles',
        type: RequestMethod.Put
    }
}
