/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { AttendanceController } from '../../controller/xbt-platform-dingtalk-service/attendance.controller'

export class AttendanceService {
    /**
     * 获取考勤统计列定义
     */
    @Request({
        server: AttendanceController.getAttendanceAttColumns
    })
    public getAttendanceAttColumns(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取考勤统计记录
     */
    @Request({
        server: AttendanceController.queryAttendanceStatistics
    })
    public queryAttendanceStatistics(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 同步考勤统计列定义
     */
    @Request({
        server: AttendanceController.syncAttendanceAttColumns
    })
    public syncAttendanceAttColumns(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
