/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { CallBackController } from '../../controller/xbt-platform-dingtalk-service/call-back.controller'

export class CallBackService {
    /**
     * callback
     */
    @Request({
        server: CallBackController.callback
    })
    public callback(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
