/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { DepartmentController } from '../../controller/xbt-platform-dingtalk-service/department.controller'

export class DepartmentService {
    /**
     * 查询全部
     */
    @Request({
        server: DepartmentController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询钉钉的所有部门
     */
    @Request({
        server: DepartmentController.getAllWx
    })
    public getAllWx(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询子部门
     */
    @Request({
        server: DepartmentController.getChildrenById
    })
    public getChildrenById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 同步全部部门
     */
    @Request({
        server: DepartmentController.syncAllDepartment
    })
    public syncAllDepartment(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
