/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { EmployeeController } from '../../controller/xbt-platform-dingtalk-service/employee.controller'

export class EmployeeService {
    /**
     * 查询全部员工
     */
    @Request({
        server: EmployeeController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: EmployeeController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 通过ID列表查询员工信息
     */
    @Request({
        server: EmployeeController.getEmployeeByIds
    })
    public getEmployeeByIds(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 通过姓名和部门id查询
     */
    @Request({
        server: EmployeeController.getEmployeeIds
    })
    public getEmployeeIds(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用部门ID查询用户列表
     */
    @Request({
        server: EmployeeController.getEmployeesByDepartmentId
    })
    public getEmployeesByDepartmentId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用部门ID列表查询用户列表
     */
    @Request({
        server: EmployeeController.getEmployeesByDepartmentIds
    })
    public getEmployeesByDepartmentIds(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询数据库中的同步员工
     */
    @Request({
        server: EmployeeController.getLocalById
    })
    public getLocalById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 同步全部员工
     */
    @Request({
        server: EmployeeController.syncAllEmployee
    })
    public syncAllEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
