/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { MessageController } from '../../controller/xbt-platform-dingtalk-service/message.controller'

export class MessageService {
    /**
     * 发送卡片消息 用这个消息好像好一点
     */
    @Request({
        server: MessageController.sendCardMessage
    })
    public sendCardMessage(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 发送超链接消息
     */
    @Request({
        server: MessageController.sendLinkMessage
    })
    public sendLinkMessage(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
