/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { RoleController } from '../../controller/xbt-platform-dingtalk-service/role.controller'

export class RoleService {
    /**
     * 获取所有角色
     */
    @Request({
        server: RoleController.getAllRoles
    })
    public getAllRoles(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取钉钉中所有角色
     */
    @Request({
        server: RoleController.getAllRolesByDingTalk
    })
    public getAllRolesByDingTalk(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 通过角色分组ID获取角色列表
     */
    @Request({
        server: RoleController.getRolesByGroupId
    })
    public getRolesByGroupId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 同步全部角色
     */
    @Request({
        server: RoleController.syncAllRoles
    })
    public syncAllRoles(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
