/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { AppController } from '@/http/controller/authorization-service/app.controller'

export class AppService {
    /**
     * 获取扫码登录地址
     */
    @Request({
        server: AppController.getQrConnectUrl
    })
    public getQrConnectUrl(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取授权路径
     */
    @Request({
        server: AppController.authorize
    })
    public authorize(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取JSConfig配置
     */
    @Request({
        server: AppController.jsConfig
    })
    public jsConfig(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取App配置
     */
    @Request({
        server: AppController.getConfig
    })
    public getConfig(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
