/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'basic'
const service = 'xbt-platform-salary-service'

export const BasicController = {
    // create
    create: {
        service,
        controller,
        path: '/api/basic/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/basic/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    }
}
