/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'c-o-s'
const service = 'xbt-platform-salary-service'

export const COSController = {
    // 创建临时Secret
    createTempSecret: {
        service,
        controller,
        path: '/api/COSController/createTempSecret',
        action: 'createTempSecret',
        type: RequestMethod.Post
    },
    // 创建临时上传链接
    createUploadUrl: {
        service,
        controller,
        path: '/api/COSController/createUploadUrl',
        action: 'createUploadUrl',
        type: RequestMethod.Post
    },
    // fileUpload
    fileUpload: {
        service,
        controller,
        path: '/api/COSController/fileUpload',
        action: 'fileUpload',
        type: RequestMethod.Post
    },
    // 获取授权URL
    generatePresignedUrl: {
        service,
        controller,
        path: '/api/COSController/generatePresignedUrl/{objectKey}',
        action: 'generatePresignedUrl',
        type: RequestMethod.Get
    }
}
