/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee-inner-reward'
const service = 'xbt-platform-salary-service'

export const EmployeeInnerRewardController = {
    // 申请
    apply: {
        service,
        controller,
        path: '/api/inner_reward/apply/{id}',
        action: 'apply',
        type: RequestMethod.Get
    },
    // 确认
    confirm: {
        service,
        controller,
        path: '/api/inner_reward/confirm',
        action: 'confirm',
        type: RequestMethod.Post
    },
    // create
    create: {
        service,
        controller,
        path: '/api/inner_reward/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/inner_reward/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // 驳回
    deny: {
        service,
        controller,
        path: '/api/inner_reward/deny',
        action: 'deny',
        type: RequestMethod.Post
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/inner_reward/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // get List
    getList: {
        service,
        controller,
        path: '/api/inner_reward/getList',
        action: 'getList',
        type: RequestMethod.Get
    },
    // update
    update: {
        service,
        controller,
        path: '/api/inner_reward/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
