/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee-salary-inform'
const service = 'xbt-platform-salary-service'

export const EmployeeSalaryInformController = {
    // 员工确认
    confirm: {
        service,
        controller,
        path: '/api/salary_inform/confirm/{id}',
        action: 'confirm',
        type: RequestMethod.Put
    },
    // 员工否认
    deny: {
        service,
        controller,
        path: '/api/salary_inform/deny/{id}',
        action: 'deny',
        type: RequestMethod.Put
    },
    // 多人下发
    informList: {
        service,
        controller,
        path: '/api/salary_inform/informList',
        action: 'informList',
        type: RequestMethod.Get
    },
    // 单人下发
    inform: {
        service,
        controller,
        path: '/api/salary_inform/informOne/{id}',
        action: 'inform',
        type: RequestMethod.Get
    }
}
