/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee-salary'
const service = 'xbt-platform-salary-service'

export const EmployeeSalaryController = {
    // create
    create: {
        service,
        controller,
        path: '/api/employeesalary/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/employeesalary/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/employeesalary/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne
    getByEmployee: {
        service,
        controller,
        path: '/api/employeesalary/getByEmployee/{employeeId}',
        action: 'getByEmployee',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/employeesalary/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // update
    update: {
        service,
        controller,
        path: '/api/employeesalary/update',
        action: 'update',
        type: RequestMethod.Post
    }
}
