/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'flow-config'
const service = 'xbt-platform-salary-service'

export const FlowConfigController = {
    // create
    create: {
        service,
        controller,
        path: '/api/flowConfig/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/flowConfig/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/flowConfig/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/flowConfig/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // get List
    getList: {
        service,
        controller,
        path: '/api/flowConfig/getList',
        action: 'getList',
        type: RequestMethod.Get
    },
    // update
    update: {
        service,
        controller,
        path: '/api/flowConfig/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
