/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'inner-reward-rule-config'
const service = 'xbt-platform-salary-service'

export const InnerRewardRuleConfigController = {
    // create
    create: {
        service,
        controller,
        path: '/api/reward_rule_config/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/reward_rule_config/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/reward_rule_config/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // getById
    getById: {
        service,
        controller,
        path: '/api/reward_rule_config/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // get List
    getList: {
        service,
        controller,
        path: '/api/reward_rule_config/getList',
        action: 'getList',
        type: RequestMethod.Get
    },
    // update
    update: {
        service,
        controller,
        path: '/api/reward_rule_config/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
