/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'month-bonus'
const service = 'xbt-platform-salary-service'

export const MonthBonusController = {
    // create
    create: {
        service,
        controller,
        path: '/api/monthBonus/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/monthBonus/delete/{employeeId}/{performanceRuleId}',
        action: 'delete',
        type: RequestMethod.Delete
    }
}
