/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'period-check'
const service = 'xbt-platform-salary-service'

export const PeriodCheckController = {
    // get All
    getAll: {
        service,
        controller,
        path: '/api/period_check/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne by employee
    getByEmployee: {
        service,
        controller,
        path: '/api/period_check/getByEmployee/{employeeId}/{month}',
        action: 'getByEmployee',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/period_check/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // getList of detail
    getDetailListByEmployee: {
        service,
        controller,
        path: '/api/period_check/getListByEmployee/{employeeId}/{month}',
        action: 'getDetailListByEmployee',
        type: RequestMethod.Get
    }
}
