/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'report'
const service = 'xbt-platform-salary-service'

export const ReportController = {
    // findOne
    getByEmployee: {
        service,
        controller,
        path: '/api/report/dept/{id}/{month}',
        action: 'getByEmployee',
        type: RequestMethod.Get
    }
}
