/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'social-security'
const service = 'xbt-platform-salary-service'

export const SocialSecurityController = {
    // export excel
    export: {
        service,
        controller,
        path: '/api/social_security/export',
        action: 'export',
        type: RequestMethod.Get
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/social_security/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/social_security/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // import excel
    import: {
        service,
        controller,
        path: '/api/social_security/import',
        action: 'import',
        type: RequestMethod.Get
    }
}
