/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'sys-dict'
const service = 'xbt-platform-salary-service'

export const SysDictController = {
    // get All
    getAll: {
        service,
        controller,
        path: '/api/sysdict/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/sysdict/getByCode/{code}',
        action: 'get',
        type: RequestMethod.Get
    },
    // get Detail
    getDetailAll: {
        service,
        controller,
        path: '/api/sysdict/getDetailAll',
        action: 'getDetailAll',
        type: RequestMethod.Get
    },
    // find Detail One
    getDetail: {
        service,
        controller,
        path: '/api/sysdict/getDetailByCode/{code}',
        action: 'getDetail',
        type: RequestMethod.Get
    }
}
