/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'tax'
const service = 'xbt-platform-salary-service'

export const TaxController = {
    // export excel
    export: {
        service,
        controller,
        path: '/api/tax/export',
        action: 'export',
        type: RequestMethod.Get
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/tax/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/tax/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // import excel
    import: {
        service,
        controller,
        path: '/api/tax/import',
        action: 'import',
        type: RequestMethod.Get
    },
    // get Tax SocialSecurity
    taxAndSocialSecurity: {
        service,
        controller,
        path: '/api/tax/taxAndSocialSecurity/{employeeId}/{month}',
        action: 'taxAndSocialSecurity',
        type: RequestMethod.Get
    }
}
