/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'test'
const service = 'xbt-platform-salary-service'

export const TestController = {
    // 核算基数按月返Json
    getMonthBonusRule: {
        service,
        controller,
        path: '/api/test/example/json/monthBonusRule',
        action: 'getMonthBonusRule',
        type: RequestMethod.Get
    },
    // 核算基数MvelJson
    getMvelRuleSource: {
        service,
        controller,
        path: '/api/test/example/json/mvel',
        action: 'getMvelRuleSource',
        type: RequestMethod.Get
    },
    // 生成指定月份工资
    create: {
        service,
        controller,
        path: '/api/test/salaryvalue/create/{month}',
        action: 'create',
        type: RequestMethod.Get
    },
    // 删除指定月份工资
    delete: {
        service,
        controller,
        path: '/api/test/salaryvalue/delete/{month}',
        action: 'delete',
        type: RequestMethod.Get
    }
}
